# Generated by Django 5.0.3 on 2024-05-10 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_paymentaccount_balance_paymentaccount_number_and_more'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.members'),
        ),
    ]
