# Generated by Django 5.0.3 on 2024-05-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_region_paymentaccount_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='region',
        ),
    ]
