# Generated by Django 5.0.3 on 2024-05-10 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_paymentaccount_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='district',
        ),
    ]
