# Generated by Django 5.0.3 on 2024-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_paymentaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='meter_indicator',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
