# Generated by Django 5.0.3 on 2024-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_paymentaccount_meter_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='last_meter_indicator',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
