# Generated by Django 5.0.3 on 2024-05-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=33549615780536966265994486523529921053, max_length=20, null=True, unique=True),
        ),
    ]
