# Generated by Django 5.0.3 on 2024-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=300649674827009459892493946223792844534, max_length=20, null=True, unique=True),
        ),
    ]
