# Generated by Django 5.0.3 on 2024-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'Обычный пользователь'), ('lawyer', 'Юрист'), ('admin', 'Админ')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=337042450789138483673146439642036329097, max_length=20, null=True, unique=True),
        ),
    ]
