# Generated by Django 5.0.3 on 2024-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_userprofile_role_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=290479508284506401997775174704244331492, max_length=20, null=True, unique=True),
        ),
    ]
