# Generated by Django 5.0.3 on 2024-05-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=156393186166095172663681473761543327187, max_length=20, null=True, unique=True),
        ),
    ]
