# Generated by Django 5.0.3 on 2024-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=46198586057958955034163828899420442816, max_length=20, null=True, unique=True),
        ),
    ]
