# Generated by Django 5.0.3 on 2024-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=144569669496447621293428156226855472942, max_length=20, null=True, unique=True),
        ),
    ]
