# Generated by Django 5.0.3 on 2024-05-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=292779457963574853752253250337144466733, max_length=20, null=True, unique=True),
        ),
    ]
