# Generated by Django 5.0.3 on 2024-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=49043661553124988804604651738911840466, max_length=20, null=True, unique=True),
        ),
    ]
