# Generated by Django 5.0.3 on 2024-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=197864608180684347833243749042761769358, max_length=20, null=True, unique=True),
        ),
    ]
