# Generated by Django 5.0.3 on 2024-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=234128354954084472129342930488233144333, max_length=20, null=True, unique=True),
        ),
    ]
