# Generated by Django 5.0.3 on 2024-05-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=38123205426560542290892672848597285969, max_length=20, null=True, unique=True),
        ),
    ]
