# Generated by Django 4.2.11 on 2024-05-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_alter_paymentaccount_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='number',
            field=models.CharField(default=25711879456736990808480255240206153925, max_length=20, null=True, unique=True),
        ),
    ]
