# Generated by Django 5.0.3 on 2024-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipt/'),
        ),
    ]
