# Generated by Django 5.0.3 on 2024-05-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='gas_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
