# Generated by Django 4.2.11 on 2024-05-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_receipt_gas_volume_receipt_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='id',
            new_name='id_p',
        ),
    ]
