# Generated by Django 5.0.3 on 2024-05-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
