# Generated by Django 5.0.3 on 2024-05-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_message_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answer', to='forum.message'),
        ),
    ]
