# Generated by Django 5.0.3 on 2024-05-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_userprofile_district'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.region'),
        ),
    ]
