# Generated by Django 5.0.3 on 2024-05-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberdetail_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdetail',
            name='price_per_m3',
            field=models.FloatField(default=0.0),
        ),
    ]
