# Generated by Django 5.0.3 on 2024-05-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_social_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetail',
            name='social',
        ),
        migrations.RemoveField(
            model_name='members',
            name='detail',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.DeleteModel(
            name='MemberDetail',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
