# Generated by Django 5.0.3 on 2024-05-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetails',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/news_img/'),
        ),
    ]
