# Generated by Django 5.0.3 on 2024-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
